# Generated by Django 3.2 on 2021-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_indexnumber_indexservices_indexservicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexservicetype',
            name='description_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='indexservicetype',
            name='description_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='indexservicetype',
            name='title_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='indexservicetype',
            name='title_3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='indexservices',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexservicetype',
            name='description',
            field=models.TextField(),
        ),
    ]
