# Generated by Django 3.2 on 2021-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_auto_20210416_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexservicetype',
            name='description_3',
            field=models.TextField(default='sai'),
        ),
    ]
