# Generated by Django 3.2 on 2021-04-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_alter_indexservicetype_description_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexservicetype',
            name='description_3',
            field=models.TextField(default=''),
        ),
    ]
