# Generated by Django 3.2 on 2021-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_alter_indexservicetype_description_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeximage',
            name='image_category',
            field=models.CharField(choices=[('wedding', 'wedding'), ('modelling', 'modelling'), ('products', 'products'), ('wildlife', 'wildlife'), ('events', 'events')], default='', max_length=50),
        ),
    ]
