# Generated by Django 3.2 on 2021-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_auto_20210417_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='facebook_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='inta_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='twitter_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='youtube_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
