# Generated by Django 3.2 on 2021-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0008_auto_20210417_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='inta_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
