# Generated by Django 3.2 on 2021-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0011_customerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='message',
            field=models.TextField(),
        ),
    ]
