# Generated by Django 3.2 on 2021-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0013_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
