# Generated by Django 3.2 on 2021-04-28 15:40

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0014_auto_20210418_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalimages',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
