# Generated by Django 3.2 on 2021-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0015_alter_totalimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
