# Generated by Django 3.2 on 2021-04-28 16:18

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0016_alter_totalimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=99, size=[100, 100], upload_to='')),
            ],
        ),
    ]
