# Generated by Django 3.2 on 2021-04-28 16:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0017_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='image_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=99, size=[500, 500], upload_to=''),
        ),
    ]
