# Generated by Django 3.2 on 2021-04-28 16:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0018_alter_demo_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='image_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=99, size=[1000, 1000], upload_to=''),
        ),
    ]
