# Generated by Django 3.2 on 2021-04-28 16:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0020_auto_20210428_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=99, size=[1000, 1000], upload_to=''),
        ),
    ]
